// List of all universities in Germany
export const GERMAN_UNIVERSITIES = [
    // Major Technical Universities (TU9)
    "RWTH Aachen University",
    "TU Berlin - Technical University of Berlin",
    "TU Braunschweig - Technical University of Braunschweig",
    "TU Darmstadt - Technical University of Darmstadt",
    "TU Dresden - Technical University of Dresden",
    "Leibniz University Hannover",
    "Karlsruhe Institute of Technology (KIT)",
    "TU München - Technical University of Munich",
    "University of Stuttgart",

    // Major Universities
    "Freie Universität Berlin (Free University of Berlin)",
    "Humboldt University of Berlin",
    "Ludwig Maximilian University of Munich (LMU)",
    "Heidelberg University",
    "University of Freiburg",
    "University of Göttingen",
    "University of Hamburg",
    "University of Cologne",
    "University of Frankfurt",
    "University of Bonn",
    "University of Münster",
    "University of Tübingen",
    "University of Würzburg",
    "University of Leipzig",
    "University of Mainz",
    "University of Erlangen-Nuremberg",
    "University of Konstanz",
    "University of Mannheim",
    "University of Regensburg",
    "University of Ulm",

    // Universities of Applied Sciences (Hochschulen)
    "Munich University of Applied Sciences",
    "Frankfurt University of Applied Sciences",
    "Hamburg University of Applied Sciences",
    "Cologne University of Applied Sciences",
    "Berlin University of Applied Sciences (HTW Berlin)",
    "Darmstadt University of Applied Sciences",
    "Esslingen University of Applied Sciences",
    "Karlsruhe University of Applied Sciences",
    "Mannheim University of Applied Sciences",
    "Nuremberg Tech",
    "Aachen University of Applied Sciences",
    "Bonn-Rhein-Sieg University of Applied Sciences",
    "Bremen University of Applied Sciences",
    "Dortmund University of Applied Sciences",
    "Düsseldorf University of Applied Sciences",
    "Hannover University of Applied Sciences",
    "Kiel University of Applied Sciences",
    "Lübeck University of Applied Sciences",
    "Magdeburg-Stendal University of Applied Sciences",
    "Mittweida University of Applied Sciences",
    "Osnabrück University of Applied Sciences",
    "Pforzheim University",
    "Reutlingen University",
    "Rosenheim Technical University of Applied Sciences",
    "Stralsund University of Applied Sciences",
    "Wiesbaden University of Applied Sciences",
    "Wismar University of Applied Sciences",

    // Other Notable Universities
    "University of Augsburg",
    "University of Bamberg",
    "University of Bayreuth",
    "Bielefeld University",
    "Ruhr University Bochum",
    "University of Bremen",
    "Chemnitz University of Technology",
    "TU Clausthal - Clausthal University of Technology",
    "University of Duisburg-Essen",
    "University of Düsseldorf",
    "University of Greifswald",
    "University of Halle-Wittenberg",
    "University of Hohenheim",
    "TU Ilmenau - Ilmenau University of Technology",
    "University of Jena",
    "University of Kaiserslautern",
    "University of Kassel",
    "University of Kiel",
    "University of Koblenz-Landau",
    "University of Lüneburg",
    "University of Marburg",
    "University of Oldenburg",
    "University of Osnabrück",
    "University of Paderborn",
    "University of Passau",
    "University of Potsdam",
    "University of Rostock",
    "Saarland University",
    "University of Siegen",
    "University of Trier",
    "University of Vechta",
    "University of Wuppertal",

    // Specialized Universities
    "German Sport University Cologne",
    "University of Music and Performing Arts Munich",
    "Berlin University of the Arts",
    "Hamburg University of Music and Theatre",
    "Bauhaus University Weimar",
    "Jacobs University Bremen",
    "Zeppelin University",
    "WHU - Otto Beisheim School of Management",
    "ESMT Berlin",
    "Frankfurt School of Finance & Management",
    "Hertie School",
    "Bucerius Law School",

    // Medical Universities
    "Charité - Universitätsmedizin Berlin",
    "Hannover Medical School",
    "Medical University of Lübeck",

    // Other
    "Other"
].sort();
